version: '3.8'

services:
  wordpress-ci:
    build:
      image: wordpress-ci:${PHP_VERSION:-8.1}
      context: ./docker
      dockerfile: ./Dockerfile
      args:
        PHP_VERSION: ${PHP_VERSION:-8.1}
    container_name: wordpress-ci
    depends_on:
      - db
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      PLUGINS_COPIED: 'true'
      THEMES_COPIED: 'true'
    volumes:
      - ./example/myplugin:/usr/src/wordpress-ci/plugins/myplugin:Z
      - ./example/mytheme:/usr/src/wordpress-ci/themes/mytheme:Z
    ports:
      - '8080:80'
    networks:
      - network

  db:
    image: mariadb:latest
    container_name: wordpress-ci-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    ports:
      - '3306:3306'
    networks:
      - network

networks:
  network:
    driver: bridge
